on:
  push:
    tags:
      - '*'

jobs:
  gh-release:
    name: gh-release
    runs-on: ubuntu-latest
    steps:
      - uses: pipe-cd/actions-gh-release@v2.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
